id: I1B08A1AA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T12:18:58+00:00'
last_modified: '2022-06-08T10:09:27.933155+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB4584
  title: རྭ་སྒྲེང་དགོན་པའི་ཉམས་བཞེས་ཆོས་སྤྱོད་ཀྱི་བརྗེད་བྱང་ཆེན་མོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0D96:
      image_group_id: I1PD33293
      title: ''
      total_pages: 978
      order: 1
      base_file: 0D96.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
