id: P009317
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:33:01.844853
source_metadata:
  id: bdr:W2DB4584
  title: རྭ་སྒྲེང་དགོན་པའི་ཉམས་བཞེས་ཆོས་སྤྱོད་ཀྱི་བརྗེད་བྱང་ཆེན་མོ
  author: ''
  volumes:
    4ed2fc7fdbd140acabe4addd793e9472:
      image_group_id: I1PD33293
      title: ''
      volume_number: 1
      total_pages: 978
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
