id: P009317
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB4584
  title: རྭ་སྒྲེང་དགོན་པའི་ཉམས་བཞེས་ཆོས་སྤྱོད་ཀྱི་བརྗེད་བྱང་ཆེན་མོ
  author: ''
  volumes:
    4ed2fc7fdbd140acabe4addd793e9472:
      image_group_id: I1PD33293
      title: ''
      volume_number: 1
      total_pages: 978
      base_file: v001.txt
